USE memopage;

-- TABLE
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS notes;

CREATE TABLE CATEGORY
(
	CATEGORY_NO 	INT 			NOT NULL,
    CATEGORY_NAME 	VARCHAR(50) 	NOT NULL,
    CATEGORY_COLOR 	VARCHAR(10) 	DEFAULT '#fffef2',
    CATEGORY_SORT 	INT 			NOT NULL,
    PRIMARY KEY (CATEGORY_NO)
);

CREATE TABLE NOTES
(
	NOTES_NO 		INT 			NOT NULL,
    CATEGORY_NO 	INT 			DEFAULT NULL,
    NOTES_TITLE 	VARCHAR(100) 	DEFAULT NULL,
    NOTES_CONTENT 	VARCHAR(2000) 	NOT NULL,
    NOTES_DATE 		TIMESTAMP 		NOT NULL,
    PRIMARY KEY (NOTES_NO),
    CONSTRAINT NOTES_CATEGORY_FK FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

-- FUNCTION
DROP FUNCTION IF EXISTS `GET_NOTES_NO`;
DROP function IF EXISTS `GET_CATEGORY_NO`;

DELIMITER $$
USE `memopage`$$
CREATE FUNCTION `GET_NOTES_NO` ()
RETURNS INT
BEGIN
	DECLARE RESULT INT;
    
     SELECT MAX(NOTES_NO)
       INTO RESULT
       FROM NOTES;
	
    IF (RESULT = NULL)
    THEN
    	SET RESULT = 0;
	ELSE
		SET RESULT = RESULT + 1;
	END IF;
    
RETURN RESULT;
END$$

DELIMITER ;


DELIMITER $$
USE `memopage`$$
CREATE FUNCTION `GET_CATEGORY_NO` ()
RETURNS INT
BEGIN
	DECLARE RESULT INT;
    
     SELECT MAX(CATEGORY_NO)
       INTO RESULT
       FROM CATEGORY;
	
    IF (RESULT = NULL)
    THEN
    	SET RESULT = 0;
	ELSE
		SET RESULT = RESULT + 1;
	END IF;
    
RETURN RESULT;
END$$

DELIMITER ;